---
kind: pipeline
name: linux-amd64

platform:
  os: linux
  arch: amd64

steps:

- name: publish
  pull: always
  image: ghcr.io/appleboy/drone-secrets:1
  settings:
    drone_token:
      from_secret: drone_token
    drone_host:
      from_secret: drone_host
    org_list: appleboy,go-training
    repo_list: go-training/golang-in-ecr-ecs,go-training/drone-git-push-example
    key_list: foobar,docker_test_username,docker_test_token
    foobar: test
  environment:
    DOCKER_TEST_USERNAME: appleboy
    DOCKER_TEST_TOKEN: 1234
